/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ErrorModal: typeof import('./components/map/ErrorModal.vue')['default']
    LeafletMap: typeof import('./components/map/LeafletMap.vue')['default']
    MapPage: typeof import('./components/map/MapPage.vue')['default']
    MobileHeader: typeof import('./components/MobileHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/map/Sidebar.vue')['default']
  }
}
